spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gcp.connect.psdb.cloud:3306/soobin_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: j8pjg3173purs2bzmyul
    password: pscale_pw_pxb5jLW2HB5fsAvmqZ1RSSQyuOLSgBZ1AZCbhJ8HZ3m
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/binsoo_db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234
    hikari:
      maximum-pool-size: 40
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.security: DEBUG

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 1800

#    spring:
#      http:
#        encoding:
#          charset: UTF-8
#          enabled: true
#          force: true
