spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gcp.connect.psdb.cloud:3306/binsoo_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: vdlz35sutluz82ohdaas
    password: pscale_pw_V6bBpp2nhp1Te7Gn3zo5eqncyHmNXXeVuwsGNAZcwCM
    hikari:
      maximum-pool-size: 40
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 1800

#    spring:
#      http:
#        encoding:
#          charset: UTF-8
#          enabled: true
#          force: true
